### ISSUE TITLE
Please provide r20p0 drivers for RK3399

### ISSUE THREAD

**Issue by shadeslayer** [rockchip-linux/libmali#43]
Hi
Could you please release the R20 drivers for libmali?

**Comment by shadeslayer** [comment]
There is currently a bug in the r14 drivers where querying GL_CONTEXT_FLAGS generates a "Invalid enum" error.

**Comment by zgrimshell** [comment]
Upvoting this as well - it would be nice to have release so it can enter distros faster and help with hw enablement.

**Comment by rastermann** [comment]
upvote too...

**Comment by skyne98** [comment]
I think even those are already dated, what about r28? Upvote as well

**Comment by rastermann** [comment]
or in general keep them up to date with regular updates/releases as time goes on.

**Comment by skyne98** [comment]
@rastermann, good point.

**Comment by mko-io** [comment]
please provide updated driver with Vulkan support

**Comment by tarelda** [comment]
I guess they chose to ignore us...

**Comment by wll1rah** [comment]
I'm not sure if any of you have tried to download the open source provided by arm, but in the meson_options.txt file it tells you how to select the driver version you wan to use.

**Comment by rastermann** [comment]
arm doesn't provide any open source drivers for mali...

**Comment by wll1rah** [comment]
> arm doesn't provide any open source drivers for mali...

They most certainly do it's just not a binary, and you have to to the configuration yourself.  It's mainly because they don't have standards.  They have them for both Linux and android.  The Linux has blobs for both the user space map driver and kernel drivers.

https://developer.arm.com/tools-and-software/graphics-and-gaming/mali-drivers/midgard-kernel

These are the same blobs that are used in this build script.  if using a blob not provided you'll just have to update the paths to the correct file/s.

enjoy

**Comment by rastermann** [comment]
They do not. They are binary blobs. They are not open source at all. You said "download the *OPEN SOURCE* provided by Arm". There is no *OPEN SOURCE* provided by Arm for Mali. Well not userspace. The kernel source is provided and needs forward-porting to newer kernels at times. The workflow is that SoC vendors get DDK source and they do any SoC errata fixups and then regularly release binaries for their SoC.

**Comment by JeffyCN** [comment]
there's no plan to update to r20, the current version is r18.

it's not that simple to update versions, the company need to buy it from arm, then do some porting.
