### ISSUE TITLE
Porting midgard r18 driver to 5.7 kernel

### ISSUE THREAD

**Issue by walkiry** [rockchip-linux/libmali#56]
Hi, will there be any support for Vulkan api on midgard?
Also will there be r28p0 library soon?  At least for GBM?

I am asking because it seems there are less effort to port the mali drivers into to the mainline kernel (and a bench of other drivers are working in the mainline and not in your custom version).

Thank you

**Comment by JeffyCN** [comment]
No and no and no.

1/ There is vulkan api on midgard, but our company didn't buy it from ARM(only bought vulkan for android platform) it's very expensive :(

2/ Again, the company bought r18 for midgard, and has no plan to buy r28 for now(i guess)

3/ That is so not true. For mainline kernel, people would always port their custom versions(for example chromeos), and there're so many versions of mali driver which are not compatible to each other.

For mainline kernel, i would suggest use panfrost.

**Comment by JeffyCN** [comment]
If you are interested about using this libmali(r18) on mainline kernel(without vulkan of cause), @Caesar-github has ported the driver personal recently.

**Comment by walkiry** [comment]
Thanks a lot. 

Well regarding the mailine,  I am talking from my own experience with your chip, i had few to no trouble booting over USB using out of the box drivers + device tree. Whereas while using the rockchip repo, I have still some issue there.

Anyway thank you again.

**Comment by JeffyCN** [comment]
hmm, you can try to port whatever you need to the local mainline kernel(from bsp 4.19 kernel or chromeos 5.4 kernel),  the bsp kernel is mostly for some bsp features(for example isp camera/video) and performance/stable tuning.


what i saying about mainline kernel and mali driver is:
1/ the mali driver should match the mali library(ddk) to get it work(there are too many versions)

2/ mali driver is open-source(only since these years), but ddk not(and needs to buy it)

so:
1/ if you have a r28 midgard driver(assuming from other people), you would have to buy a r28 midgard ddk to use it
2/ if you have a r18 midgard ddk, and want to use it on mainline kernel, you would have to port the r18 midgard driver to mainline(there's no other way, unless using open sourced panfrost driver/userspace)

we(rockchip) have open sourced r14/r18 midgard driver and ddk

chromeos(google) has r13/r14/r25... midgard drivers and ddk(for gbm only, and some older version for x11)

**Comment by walkiry** [comment]
>  1/ the mali driver should match the mali library(ddk) to get it work(there are too many versions).
I did not know that, I had experienced it porting driver r18p0 into the kernel 5.7.10. It is not clearly said on the ARM website whether or not it would be retro-compatible. 

> 2/ if you have a r18 midgard ddk, and want to use it on mainline kernel, you would have to port the r18 midgard driver to mainline(there's no other way, unless using open sourced panfrost driver/userspace)
Yea sure, panfrost would be a good thing to use ( i started with it) but I am not sure about the performances. Maybe in the future....

Anyway, from my experience, after realizing that porting drivers r28p0 would not work with your DDK, I did tried to port mali r18p0 drivers into 5.7.10.
I was excited as I got the /dev/mali0 (probed worked!!!) but then when it started to ran the application using gbm, as I expected, I ran into some kernel panic issue related to the mmap and the mmu. I guess a lot has changed in the kernel API since the time when the r18p0 mali arm's driver was written and now.

Anyway, I will try to solve this issues and use your 18 binary blob. If not try to take the one from chrome-OS.
I was thinking about starting a blog to dig into the details and explain to the community what has to be done to get the best of the the rk3399 (amputed from its vulkan api). I will post here the link once i started to do so.

**Comment by JeffyCN** [comment]
For the porting, @Caesar-github  has done that recently(from https://github.com/rockchip-linux/kernel/tree/develop-4.19/drivers/gpu/arm/midgard)

@Caesar-github could you provide patches here?

**Comment by walkiry** [comment]
yes i will provide the patch for the version 5.7.10 soon later (do not have access to my machine now).

**Comment by Caesar-github** [comment]
About the mali patches: 

If you need,  I can send it to via with my email( wxt@rock-chips.com), not here.

-Caesar

**Comment by JeffyCN** [comment]
patch provided
