### ISSUE TITLE
An issue when installing

### ISSUE THREAD

**Issue by rose-jinyang** [rockchip-linux/libmali#63]
Hello
How are you?
Thanks for contributing to this project.
I have a RK3399 device on which Ubuntu 18.04 64 bit and OpenCL 1.2 are installed.
I am going to upgrade OpenCL version by using this repo.
I cloned this repo and ran "meson install" command.
But I met the following issue.

![image](https://user-images.githubusercontent.com/47862419/103797087-f4ebd980-5082-11eb-999f-7aef05152959.png)

Please let me know how to fix this issue asap.
Thanks.

**Comment by JeffyCN** [comment]
as the version requirement in meson.build:
meson_version : '>=0.49.0'

please upgrade your meson tool

**Comment by rose-jinyang** [comment]
Thanks for the quick reply.

**Comment by rose-jinyang** [comment]
I can NOT install this deb package with a general sudo dpkg command.

![image](https://user-images.githubusercontent.com/47862419/103875043-df22f680-510c-11eb-9cfb-b4ca14ecac61.png)

**Comment by JeffyCN** [comment]
That error means you have a libmali-rk-midgard-t86x-r14p0 currently installed, which is conflict with the new package.
So try remove it firstly(sudo apt-get remove libmali-rk-midgard-t86x-r14p0).

And please note that *the mali library should match the kernel's mali driver*, so if you are using r14 mali driver, choose libmali-midgard-t86x-r14p0-x11_1.9-1_arm64.deb instead of libmali-midgard-t86x-r18p0-x11_1.9-1_arm64.deb

**Comment by rose-jinyang** [comment]
Yes, OpenCL 1.2 has been installed on my RK3399 Ubuntu 18.04 aarch64.
The libOpenCL.so links to libmali-rk-midgard-t86x-r14p0.so.
I am going to upgrade the OpenCL version.
So I tried to upgrade OpenCL with your deb package libmali-midgard-t86x-r18p0-x11_1.9-1_arm64.deb.
But if the mali library that I want to install should be matched with kernel's mali driver version, does it mean that OpenCL version upgrading is impossible?

**Comment by JeffyCN** [comment]
yes, unless upgrading the driver as well.

but as far as i know, the midgard only support opencl 1.2, so upgrading to r18 would not change opencl version :(
